//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.6.6.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

export interface Entity {}

export interface IndexdEntity<T> extends Entity {
  Id: T;
}

export interface PlayList extends IndexdEntity<number> {
  Name: string;
  Tracks?: Track[];
  Context?: MusicContext;
}

export interface Track extends IndexdEntity<number> {
  Name?: string;
  Source?: string;
  Licence?: string;
  File: StoredFile;
  PlayLists?: PlayList[];
  Context?: MusicContext;
}

export interface StoredFile extends IndexdEntity<number> {
  OriginName: string;
  Extension?: string;
  CreatedAt: Date;
  StoredPath?: string;
  AssignedTrack?: Track;
}

export interface MusicContext extends IndexdEntity<number> {
  ContextId: string;
  PlayLists?: PlayList[];
  Tracks?: Track[];
}
